### ISSUE TITLE
Sort parameter issue

### ISSUE THREAD

**Issue by sgurin** [yunusga/postcss-sort-media-queries#20]
Hi!

Thanks a lot for such a useful plugin. I faced with issue when variable sort: 'desktop-first' is undefined in my build and plugin works without any issues. It doesn't arrange in the correct order only combine media queries in groups. Of course it my fault that I forgot to pass the correct variable. But there should be some foolproof. For example checks variable for undefined and NULL and reset to the default value mobile-first in that case.

**Comment by yunusga** [comment]
**Why GitHub not send notifications about new Issues?!**

@sgurin How `sort: 'desktop-first'` torned out `undefined`? Do you have any examples of code?

**Comment by sgurin** [comment]
Hi, we have already fixed that in PR https://github.com/justcoded/web-starter-kit-wp/commit/72c7fba13f8fefb5393d24942ad713d3ba2143aa So, we just forgot to define sorType: '' when we called function in our build task https://github.com/justcoded/web-starter-kit-wp/blob/master/tasks/build-styles.js

**Comment by Kassaila** [comment]
Hello, there. I fix the problem for our mistake in your plugin and create PR #22

**Comment by yunusga** [comment]
@Kassaila published in [1.4.23](https://www.npmjs.com/package/postcss-sort-media-queries/v/1.4.23)
