### ISSUE TITLE
Compatibility with PostCSS 8

### ISSUE THREAD

**Issue by jonnitto** [yunusga/postcss-sort-media-queries#24]
**Thanks for your PostCSS plugin!** 

As you probably know, [PostCSS 8] was released a few days ago. It would be great if you could make this plugin compatible with the latest version. The creators of the project have even released this [migration guide].

[PostCSS 8]: https://github.com/postcss/postcss/releases/tag/8.0.0
[migration guide]: https://evilmartians.com/chronicles/postcss-8-plugin-migration

**Comment by yunusga** [comment]
@jonnitto sorry, GitHub don't send notifications about new issues.

**Comment by Lustmored** [comment]
@yunusga could you please tell us the reason for "wontfix" label? Is it something impossible with this library or do you have no resources to do so? I'm not an expert in the field, but could try to come up with a PR if there are no blocking issues :)

**Comment by yunusga** [comment]
PR Welcome. I planed mirating to PostCSS 8 at saturday.

**Comment by Lustmored** [comment]
@yunusga Happy to help :) I've created PR for this :)

**Comment by yunusga** [comment]
@Lustmored big thanks. Job done [v2.0.3](https://github.com/yunusga/postcss-sort-media-queries/releases/tag/v2.0.3)

**Comment by yunusga** [comment]
https://github.com/CarbonPackages/Carbon.Rollup/issues/11
